export const REQUEST_MOVIES_DATA = 'REQUEST_MOVIES_DATA';
export const STORE_MOVIES_DATA = 'STORE_MOVIES_DATA';
export const ADD_MOVIE_TO_LIST = 'ADD_MOVIE_TO_LIST';
export const REMOVE_MOVIE_FROM_LIST = 'REMOVE_MOVIE_FROM_LIST';
